Loading training set...
/home/ubuntu/.local/lib/python3.13/site-packages/torch/utils/data/sampler.py:68: UserWarning: `data_source` argument is not used and will be removed in 2.2.0.You may still have custom implementation that utilizes it.
  warnings.warn(
/home/ubuntu/.local/lib/python3.13/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Num images:  20
Image shape: [3, 64, 64]
Label shape: [0]

Constructing networks...
Traceback (most recent call last):
  File "/workspace/train/runpod-hf/vendor/stylegan2ada/train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
    ~~~~^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/train/runpod-hf/vendor/stylegan2ada/train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/train/runpod-hf/vendor/stylegan2ada/train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/workspace/train/runpod-hf/vendor/stylegan2ada/training/training_loop.py", line 150, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1369, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/nn/modules/module.py", line 928, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/nn/modules/module.py", line 928, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/nn/modules/module.py", line 928, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  [Previous line repeated 1 more time]
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/nn/modules/module.py", line 955, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1355, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/cuda/__init__.py", line 412, in _lazy_init
    torch._C._cuda_init()
    ~~~~~~~~~~~~~~~~~~~^^
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Exception ignored in atexit callback <function _exit_function at 0x7fcb33c01ee0>:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/util.py", line 349, in _exit_function
    p.join()
  File "/usr/lib/python3.13/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.13/multiprocessing/popen_fork.py", line 44, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.13/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/torch/utils/data/_utils/signal_handling.py", line 73, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 9273) is killed by signal: Terminated. 
